### ISSUE TITLE
Не получается загрузить ISO

### ISSUE THREAD

**Issue by LOKJHTE** [magos-linux/magos-linux#16]
Зашёл на официальный сайт дистрибутива https://magos-linux.ru через браузер Vivaldi установленный на дистрибутив Vannila OS, мне лично нравиться устанавливать разные дистрибутивы и изучать их, обе ссылки для скачивания ISO не дают нормально его загрузить, HHTP ведёт на страницу где есть что-то похожее на ссылки для загрузки, только они не работают сколько бы я не кликал на них нечего не меняется, когда я попытался открыть эти ссылки в новой вкладки открывается просто пустая страница, вторая ссылка FTP при нажатие просит открыть предложение "xdg-open" при открытии открывается новое окно браузера, с пустой страницей без названия, но только в отличии от ссылок из HHTP там уже какой-то фон. 
Вот скрин того что открывает FTP: 
![FTPMagOS](https://github.com/magos-linux/magos-linux/assets/161603562/3222367e-f9d8-446f-9ffa-f1f4cdd15902)
А вот ссылка на то что открывается при нажатие на HHTP:
http://ftp.magos-linux.ru/iso/

**Comment by LOKJHTE** [comment]
_Может кто то знает где скачать нормальной ISO файл для последующей установки этого дистрибутива? Если да то пожалуйста объясните что делать._

**Comment by ilfat12** [comment]
Может через прямую ссылку получится?
http://ftp.magos-linux.ru/iso/MagOS_2021_20240223.iso

**Comment by LOKJHTE** [comment]
Спасибо за ответ, на ноутбуке загрузка снова не работает, просто белый экран. Но похоже это что то с браузером или Vanilla OS, я попробовал через телефон там всё работает, попробую через другой браузер на ноутбуке установить ISO.

**Comment by LOKJHTE** [comment]
Через встроенный из коробки браузер загрузка по вашей ссылке пошла. Ещё раз спасибо.
